// generated by scripts/liturgy/build-propers.mjs — do not edit by hand.
// Vite-safe: plain dynamic import() of a .json file, NO import attribute. Vite/Rollup inline
// JSON into a JS module at build time regardless (verified: the emitted dynamic-import chunk is
// already .js, not .json), and the dev server serves it as `text/javascript` — an import
// attribute of `{ with: { type: 'json' } }` here would make a real browser reject that response
// (MIME mismatch) even though it round-trips fine at build time. Node executing this file
// directly would fail (`ERR_IMPORT_ATTRIBUTE_MISSING`) for the same reason browsers would reject
// the attributed form — which is why resolveLiturgyForDate() accepts an injectable ChunkFetcher:
// Node-side callers (verify-propers.mjs, coverage-report.mjs) supply an fs-based one instead of
// importing this module at all.
export const CHUNK_LOADERS = {
  'advent': () => import('./advent.json'),
  'christmas': () => import('./christmas.json'),
  'easter': () => import('./easter.json'),
  'holyweek': () => import('./holyweek.json'),
  'lent': () => import('./lent.json'),
  'ot': () => import('./ot.json'),
  'sanctoral': () => import('./sanctoral.json'),
}
