#!/usr/bin/env node
// Builds the app's New Testament store: joins the harvested Portuguese (Matos
// Soares 1956) with the repaired Clementine Vulgate and emits one committed JSON
// chunk per book plus the Vite-safe loader map. BUILD-TIME ONLY.
//
//   node scripts/nt/harvest-pt.mjs      # 27 requests, cached
//   node scripts/nt/verify-pt.mjs       # alignment + oracle + shape
//   node scripts/nt/build-nt.mjs        # -> src/data/nt/books/*.json + chunks.ts
//
// One chunk per book (not per season like the liturgy store) because that is the
// unit the reader actually loads: you stay inside one book for weeks of 5-minute
// readings, and the largest book is ~200 KB.
//
// Verses are stored as ARRAYS in verse order, not objects keyed by number: the
// reader renders a book start-to-finish and only ever needs sequential access, and
// an array survives JSON round-trips without key-ordering assumptions.

import { mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { NT_BOOKS } from '../../src/data/nt/books.ts'
import { loadLatinNt } from './lib/latin.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PT_DIR = path.join(__dirname, '.cache', 'pt')
const OUT_DIR = path.join(__dirname, '..', '..', 'src', 'data', 'nt', 'books')
const CHUNKS_PATH = path.join(__dirname, '..', '..', 'src', 'data', 'nt', 'chunks.ts')

function formatBytes(n) {
  return n < 1024 * 1024 ? `${(n / 1024).toFixed(0)} KB` : `${(n / 1024 / 1024).toFixed(2)} MB`
}

async function main() {
  const { latin, applied } = await loadLatinNt()
  for (const a of applied) console.log(`[build-nt] latin repair: ${a}`)

  await mkdir(OUT_DIR, { recursive: true })
  // Drop stale chunks so a renamed/removed book can't linger in the bundle.
  for (const f of await readdir(OUT_DIR).catch(() => [])) {
    if (f.endsWith('.json')) await rm(path.join(OUT_DIR, f))
  }

  let totalBytes = 0
  let totalVerses = 0
  let missingLatin = 0
  const rows = []

  for (const book of NT_BOOKS) {
    let pt
    try {
      pt = JSON.parse(await readFile(path.join(PT_DIR, `${book.key}.json`), 'utf8'))
    } catch {
      throw new Error(
        `[build-nt] no harvested Portuguese for ${book.key} — run \`node scripts/nt/harvest-pt.mjs\` first`
      )
    }

    const chapters = {}
    let bookVerses = 0
    for (let c = 1; c <= book.chapters; c++) {
      const ptChapter = pt.chapters[c]
      if (!ptChapter) throw new Error(`[build-nt] ${book.key}: missing chapter ${c}`)
      const laChapter = latin[book.key]?.[String(c)] ?? {}
      const verseNums = Object.keys(ptChapter)
        .map(Number)
        .sort((a, b) => a - b)
      chapters[c] = verseNums.map((v) => {
        const la = laChapter[String(v)]
        if (!la) missingLatin++
        // `la` omitted rather than empty-stringed: the reader tests presence to
        // decide whether a verse can be shown in Latin at all.
        return la ? { v, pt: ptChapter[v], la } : { v, pt: ptChapter[v] }
      })
      bookVerses += verseNums.length
    }

    const json = JSON.stringify({ key: book.key, chapters })
    const outPath = path.join(OUT_DIR, `${book.key}.json`)
    await writeFile(outPath, json, 'utf8')
    totalBytes += json.length
    totalVerses += bookVerses
    rows.push({ key: book.key, name: book.name, chapters: book.chapters, verses: bookVerses, bytes: json.length })
  }

  const loaderEntries = NT_BOOKS.map((b) => `  '${b.key}': () => import('./books/${b.key}.json'),`).join('\n')
  await writeFile(
    CHUNKS_PATH,
    `// generated by scripts/nt/build-nt.mjs — do not edit by hand.
// Vite-safe: plain dynamic import() of a .json file, NO import attribute. Vite/Rollup
// inline JSON into a JS module at build time regardless, and the dev server serves it
// as \`text/javascript\` — an import attribute of \`{ with: { type: 'json' } }\` would make
// the browser reject that response on a MIME mismatch. Same reasoning (and the same
// hard-won bug) as src/data/liturgy/propers/chunks.ts.
export const NT_CHUNK_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
${loaderEntries}
}
`,
    'utf8'
  )

  for (const r of rows) {
    console.log(
      `[build-nt] ${r.key.padEnd(7)} ${String(r.chapters).padStart(2)} ch  ${String(r.verses).padStart(4)} vv  ${formatBytes(r.bytes).padStart(7)}  ${r.name}`
    )
  }
  console.log(
    `\n[build-nt] ${rows.length} books, ${totalVerses} verses, ${formatBytes(totalBytes)} total (largest ${formatBytes(Math.max(...rows.map((r) => r.bytes)))})`
  )
  console.log(
    missingLatin === 0
      ? '[build-nt] every verse has both Portuguese and Latin'
      : `[build-nt] ${missingLatin} verse(s) have no Latin (reader falls back to Portuguese)`
  )
  console.log(`[build-nt] wrote ${OUT_DIR}`)
  console.log(`[build-nt] wrote ${CHUNKS_PATH}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
