// generated by scripts/nt/build-nt.mjs — do not edit by hand.
// Vite-safe: plain dynamic import() of a .json file, NO import attribute. Vite/Rollup
// inline JSON into a JS module at build time regardless, and the dev server serves it
// as `text/javascript` — an import attribute of `{ with: { type: 'json' } }` would make
// the browser reject that response on a MIME mismatch. Same reasoning (and the same
// hard-won bug) as src/data/liturgy/propers/chunks.ts.
export const NT_CHUNK_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
  'Matt': () => import('./books/Matt.json'),
  'Mark': () => import('./books/Mark.json'),
  'Luke': () => import('./books/Luke.json'),
  'John': () => import('./books/John.json'),
  'Acts': () => import('./books/Acts.json'),
  'Rom': () => import('./books/Rom.json'),
  '1Cor': () => import('./books/1Cor.json'),
  '2Cor': () => import('./books/2Cor.json'),
  'Gal': () => import('./books/Gal.json'),
  'Eph': () => import('./books/Eph.json'),
  'Phil': () => import('./books/Phil.json'),
  'Col': () => import('./books/Col.json'),
  '1Thess': () => import('./books/1Thess.json'),
  '2Thess': () => import('./books/2Thess.json'),
  '1Tim': () => import('./books/1Tim.json'),
  '2Tim': () => import('./books/2Tim.json'),
  'Titus': () => import('./books/Titus.json'),
  'Phlm': () => import('./books/Phlm.json'),
  'Heb': () => import('./books/Heb.json'),
  'Jas': () => import('./books/Jas.json'),
  '1Pet': () => import('./books/1Pet.json'),
  '2Pet': () => import('./books/2Pet.json'),
  '1John': () => import('./books/1John.json'),
  '2John': () => import('./books/2John.json'),
  '3John': () => import('./books/3John.json'),
  'Jude': () => import('./books/Jude.json'),
  'Rev': () => import('./books/Rev.json'),
}
