// New Testament text — runtime loader.
//
// CONTRACT FILE: the UI (NovoTestamentoView) imports only these types and
// `loadNtBook`. One lazily-imported chunk per book (generated by
// scripts/nt/build-nt.mjs into ./books/<key>.json), cached forever once fetched —
// the text is immutable, so there is nothing to invalidate.
//
// Portuguese: Pe. Matos Soares, 1956 edition. Latin: the Clementine Vulgate, from
// the SAME cache the Liturgia do Dia store was built from, so the daily readings and
// this reader can never disagree about a verse. Versification is identical between
// the two (Matos Soares translated from the Vulgate) — verified chapter by chapter
// at build time — which is what makes the interlinear mode possible.

import { NT_CHUNK_LOADERS } from './chunks.ts'
import { getNtBook } from './books.ts'

export interface NtVerse {
  v: number
  pt: string
  /** Absent only if the Vulgate lacks the verse; the reader then falls back to pt. */
  la?: string
}

export interface NtBookText {
  key: string
  /** Keyed by chapter number as a string (JSON object keys). Verses are in order. */
  chapters: Record<string, NtVerse[]>
}

const cache = new Map<string, Promise<NtBookText | undefined>>()

/**
 * Load one book's full bilingual text. Resolves to undefined for an unknown key
 * (rather than throwing) so a stale saved position can't crash the reader — callers
 * fall back to the first book.
 */
export function loadNtBook(key: string): Promise<NtBookText | undefined> {
  let pending = cache.get(key)
  if (!pending) {
    const loader = NT_CHUNK_LOADERS[key]
    pending = loader
      ? loader().then((m) => (m as { default: NtBookText }).default)
      : Promise.resolve(undefined)
    cache.set(key, pending)
  }
  return pending
}

/** Chapter numbers of a loaded book, ascending. */
export function chapterNumbers(book: NtBookText): number[] {
  return Object.keys(book.chapters)
    .map(Number)
    .sort((a, b) => a - b)
}

/**
 * Clamp a (possibly stale) saved position onto a loaded book: a chapter or verse
 * that no longer exists resolves to the nearest one that does, so the reader always
 * has somewhere valid to scroll to.
 */
export function clampToBook(
  book: NtBookText,
  chapter: number,
  verse: number
): { chapter: number; verse: number } {
  const chapters = chapterNumbers(book)
  if (chapters.length === 0) return { chapter: 1, verse: 1 }
  const c = chapters.includes(chapter) ? chapter : chapters[0]
  const verses = book.chapters[String(c)] ?? []
  const v = verses.some((x) => x.v === verse) ? verse : (verses[0]?.v ?? 1)
  return { chapter: c, verse: v }
}

/** Display label for a position, e.g. "São Mateus 5,21". */
export function formatReference(bookKey: string, chapter: number, verse?: number): string {
  const book = getNtBook(bookKey)
  const name = book?.name ?? bookKey
  return verse ? `${name} ${chapter},${verse}` : `${name} ${chapter}`
}
